export enum PopupsActionType {
	POPUPS_SNACKBAR = 'POPUPS_SNACKBAR',
	POPUPS_MSG = 'POPUPS_MSG',
	POPUPS_FULLSCREEN = 'POPUPS_FULLSCREEN',
	POPUPS_GLOBAL_SLIDING_POPUP = 'POPUPS_GLOBAL_SLIDING_POPUP',
	POPUPS_GLOBAL_POPUP_BASE = 'POPUPS_GLOBAL_POPUP_BASE',
}
